version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000
    command: /app/cmd/server

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/app/cmd/agent -server server:5050 -destination http://web-app:2368"
    depends_on:
      - server
    restart: on-failure

  web-app:
    image: ghost 
    environment:
      - "url=http://proxy.local"

